export const sortingTypes = ["이름순", "인기순", "세팅일순", "거리순"];
export const sortingTypeToQuery = (type: string) => {
  switch (type) {
    case "이름순":
      return "NAME";
    case "인기순":
      return "POPU";
    case "세팅일순":
      return "LATE";
    case "거리순":
      return "DIST";
    default:
      return "NAME";
  }
};

export const queryToSortingType = (query: string) => {
  switch (query) {
    case "NAME":
      return "이름순";
    case "POPU":
      return "인기순";
    case "LATE":
      return "세팅일순";
    case "DIST":
      return "거리순";
    default:
      return "이름순";
  }
};

export const DISTRCIT_CITY_DATA = [
  {
    id: "1",
    city: "서울특별시",
    cityDistrict: "서울특별시",
  },
  {
    id: "2",
    city: "서울특별시",
    district: "종로구",
    cityDistrict: "서울특별시 종로구",
  },
  {
    id: "3",
    city: "서울특별시",
    district: "중구",
    cityDistrict: "서울특별시 중구",
  },
  {
    id: "4",
    city: "서울특별시",
    district: "용산구",
    cityDistrict: "서울특별시 용산구",
  },
  {
    id: "5",
    city: "서울특별시",
    district: "성동구",
    cityDistrict: "서울특별시 성동구",
  },
  {
    id: "6",
    city: "서울특별시",
    district: "광진구",
    cityDistrict: "서울특별시 광진구",
  },
  {
    id: "7",
    city: "서울특별시",
    district: "동대문구",
    cityDistrict: "서울특별시 동대문구",
  },
  {
    id: "8",
    city: "서울특별시",
    district: "중랑구",
    cityDistrict: "서울특별시 중랑구",
  },
  {
    id: "9",
    city: "서울특별시",
    district: "성북구",
    cityDistrict: "서울특별시 성북구",
  },
  {
    id: "10",
    city: "서울특별시",
    district: "강북구",
    cityDistrict: "서울특별시 강북구",
  },
  {
    id: "11",
    city: "서울특별시",
    district: "도봉구",
    cityDistrict: "서울특별시 도봉구",
  },
  {
    id: "12",
    city: "서울특별시",
    district: "노원구",
    cityDistrict: "서울특별시 노원구",
  },
  {
    id: "13",
    city: "서울특별시",
    district: "은평구",
    cityDistrict: "서울특별시 은평구",
  },
  {
    id: "14",
    city: "서울특별시",
    district: "서대문구",
    cityDistrict: "서울특별시 서대문구",
  },
  {
    id: "15",
    city: "서울특별시",
    district: "마포구",
    cityDistrict: "서울특별시 마포구",
  },
  {
    id: "16",
    city: "서울특별시",
    district: "양천구",
    cityDistrict: "서울특별시 양천구",
  },
  {
    id: "17",
    city: "서울특별시",
    district: "강서구",
    cityDistrict: "서울특별시 강서구",
  },
  {
    id: "18",
    city: "서울특별시",
    district: "구로구",
    cityDistrict: "서울특별시 구로구",
  },
  {
    id: "19",
    city: "서울특별시",
    district: "금천구",
    cityDistrict: "서울특별시 금천구",
  },
  {
    id: "20",
    city: "서울특별시",
    district: "영등포구",
    cityDistrict: "서울특별시 영등포구",
  },
  {
    id: "21",
    city: "서울특별시",
    district: "동작구",
    cityDistrict: "서울특별시 동작구",
  },
  {
    id: "22",
    city: "서울특별시",
    district: "관악구",
    cityDistrict: "서울특별시 관악구",
  },
  {
    id: "23",
    city: "서울특별시",
    district: "서초구",
    cityDistrict: "서울특별시 서초구",
  },
  {
    id: "24",
    city: "서울특별시",
    district: "강남구",
    cityDistrict: "서울특별시 강남구",
  },
  {
    id: "25",
    city: "서울특별시",
    district: "송파구",
    cityDistrict: "서울특별시 송파구",
  },
  {
    id: "26",
    city: "서울특별시",
    district: "강동구",
    cityDistrict: "서울특별시 강동구",
  },
  {
    id: "27",
    city: "부산광역시",
    cityDistrict: "부산광역시",
  },
  {
    id: "28",
    city: "부산광역시",
    district: "중구",
    cityDistrict: "부산광역시 중구",
  },
  {
    id: "29",
    city: "부산광역시",
    district: "서구",
    cityDistrict: "부산광역시 서구",
  },
  {
    id: "30",
    city: "부산광역시",
    district: "동구",
    cityDistrict: "부산광역시 동구",
  },
  {
    id: "31",
    city: "부산광역시",
    district: "영도구",
    cityDistrict: "부산광역시 영도구",
  },
  {
    id: "32",
    city: "부산광역시",
    district: "부산진구",
    cityDistrict: "부산광역시 부산진구",
  },
  {
    id: "33",
    city: "부산광역시",
    district: "동래구",
    cityDistrict: "부산광역시 동래구",
  },
  {
    id: "34",
    city: "부산광역시",
    district: "남구",
    cityDistrict: "부산광역시 남구",
  },
  {
    id: "35",
    city: "부산광역시",
    district: "북구",
    cityDistrict: "부산광역시 북구",
  },
  {
    id: "36",
    city: "부산광역시",
    district: "해운대구",
    cityDistrict: "부산광역시 해운대구",
  },
  {
    id: "37",
    city: "부산광역시",
    district: "사하구",
    cityDistrict: "부산광역시 사하구",
  },
  {
    id: "38",
    city: "부산광역시",
    district: "금정구",
    cityDistrict: "부산광역시 금정구",
  },
  {
    id: "39",
    city: "부산광역시",
    district: "강서구",
    cityDistrict: "부산광역시 강서구",
  },
  {
    id: "40",
    city: "부산광역시",
    district: "연제구",
    cityDistrict: "부산광역시 연제구",
  },
  {
    id: "41",
    city: "부산광역시",
    district: "수영구",
    cityDistrict: "부산광역시 수영구",
  },
  {
    id: "42",
    city: "부산광역시",
    district: "사상구",
    cityDistrict: "부산광역시 사상구",
  },
  {
    id: "43",
    city: "부산광역시",
    district: "기장군",
    cityDistrict: "부산광역시 기장군",
  },
  {
    id: "44",
    city: "대구광역시",
    cityDistrict: "대구광역시",
  },
  {
    id: "45",
    city: "대구광역시",
    district: "중구",
    cityDistrict: "대구광역시 중구",
  },
  {
    id: "46",
    city: "대구광역시",
    district: "동구",
    cityDistrict: "대구광역시 동구",
  },
  {
    id: "47",
    city: "대구광역시",
    district: "서구",
    cityDistrict: "대구광역시 서구",
  },
  {
    id: "48",
    city: "대구광역시",
    district: "남구",
    cityDistrict: "대구광역시 남구",
  },
  {
    id: "49",
    city: "대구광역시",
    district: "북구",
    cityDistrict: "대구광역시 북구",
  },
  {
    id: "50",
    city: "대구광역시",
    district: "수성구",
    cityDistrict: "대구광역시 수성구",
  },
  {
    id: "51",
    city: "대구광역시",
    district: "달서구",
    cityDistrict: "대구광역시 달서구",
  },
  {
    id: "52",
    city: "대구광역시",
    district: "달성군",
    cityDistrict: "대구광역시 달성군",
  },
  {
    id: "53",
    city: "대구광역시",
    district: "군위군",
    cityDistrict: "대구광역시 군위군",
  },
  {
    id: "54",
    city: "인천광역시",
    cityDistrict: "인천광역시",
  },
  {
    id: "55",
    city: "인천광역시",
    district: "중구",
    cityDistrict: "인천광역시 중구",
  },
  {
    id: "56",
    city: "인천광역시",
    district: "동구",
    cityDistrict: "인천광역시 동구",
  },
  {
    id: "57",
    city: "인천광역시",
    district: "미추홀구",
    cityDistrict: "인천광역시 미추홀구",
  },
  {
    id: "58",
    city: "인천광역시",
    district: "연수구",
    cityDistrict: "인천광역시 연수구",
  },
  {
    id: "59",
    city: "인천광역시",
    district: "남동구",
    cityDistrict: "인천광역시 남동구",
  },
  {
    id: "60",
    city: "인천광역시",
    district: "부평구",
    cityDistrict: "인천광역시 부평구",
  },
  {
    id: "61",
    city: "인천광역시",
    district: "계양구",
    cityDistrict: "인천광역시 계양구",
  },
  {
    id: "62",
    city: "인천광역시",
    district: "서구",
    cityDistrict: "인천광역시 서구",
  },
  {
    id: "63",
    city: "인천광역시",
    district: "강화군",
    cityDistrict: "인천광역시 강화군",
  },
  {
    id: "64",
    city: "인천광역시",
    district: "옹진군",
    cityDistrict: "인천광역시 옹진군",
  },
  {
    id: "65",
    city: "광주광역시",
    cityDistrict: "광주광역시",
  },
  {
    id: "66",
    city: "광주광역시",
    district: "동구",
    cityDistrict: "광주광역시 동구",
  },
  {
    id: "67",
    city: "광주광역시",
    district: "서구",
    cityDistrict: "광주광역시 서구",
  },
  {
    id: "68",
    city: "광주광역시",
    district: "남구",
    cityDistrict: "광주광역시 남구",
  },
  {
    id: "69",
    city: "광주광역시",
    district: "북구",
    cityDistrict: "광주광역시 북구",
  },
  {
    id: "70",
    city: "광주광역시",
    district: "광산구",
    cityDistrict: "광주광역시 광산구",
  },
  {
    id: "71",
    city: "대전광역시",
    cityDistrict: "대전광역시",
  },
  {
    id: "72",
    city: "대전광역시",
    district: "동구",
    cityDistrict: "대전광역시 동구",
  },
  {
    id: "73",
    city: "대전광역시",
    district: "중구",
    cityDistrict: "대전광역시 중구",
  },
  {
    id: "74",
    city: "대전광역시",
    district: "서구",
    cityDistrict: "대전광역시 서구",
  },
  {
    id: "75",
    city: "대전광역시",
    district: "유성구",
    cityDistrict: "대전광역시 유성구",
  },
  {
    id: "76",
    city: "대전광역시",
    district: "대덕구",
    cityDistrict: "대전광역시 대덕구",
  },
  {
    id: "77",
    city: "울산광역시",
    cityDistrict: "울산광역시",
  },
  {
    id: "78",
    city: "울산광역시",
    district: "중구",
    cityDistrict: "울산광역시 중구",
  },
  {
    id: "79",
    city: "울산광역시",
    district: "남구",
    cityDistrict: "울산광역시 남구",
  },
  {
    id: "80",
    city: "울산광역시",
    district: "동구",
    cityDistrict: "울산광역시 동구",
  },
  {
    id: "81",
    city: "울산광역시",
    district: "북구",
    cityDistrict: "울산광역시 북구",
  },
  {
    id: "82",
    city: "울산광역시",
    district: "울주군",
    cityDistrict: "울산광역시 울주군",
  },
  {
    id: "83",
    city: "세종특별자치시",
    cityDistrict: "세종특별자치시",
  },
  {
    id: "84",
    city: "세종특별자치시",
    district: "세종시",
    cityDistrict: "세종특별자치시 세종시",
  },
  {
    id: "85",
    city: "경기도",
    cityDistrict: "경기도",
  },
  {
    id: "86",
    city: "경기도",
    district: "수원시",
    cityDistrict: "경기도 수원시",
  },
  {
    id: "87",
    city: "경기도",
    district: "장안구",
    cityDistrict: "경기도 장안구",
  },
  {
    id: "88",
    city: "경기도",
    district: "권선구",
    cityDistrict: "경기도 권선구",
  },
  {
    id: "89",
    city: "경기도",
    district: "팔달구",
    cityDistrict: "경기도 팔달구",
  },
  {
    id: "90",
    city: "경기도",
    district: "영통구",
    cityDistrict: "경기도 영통구",
  },
  {
    id: "91",
    city: "경기도",
    district: "성남시",
    cityDistrict: "경기도 성남시",
  },
  {
    id: "92",
    city: "경기도",
    district: "수정구",
    cityDistrict: "경기도 수정구",
  },
  {
    id: "93",
    city: "경기도",
    district: "중원구",
    cityDistrict: "경기도 중원구",
  },
  {
    id: "94",
    city: "경기도",
    district: "분당구",
    cityDistrict: "경기도 분당구",
  },
  {
    id: "95",
    city: "경기도",
    district: "의정부시",
    cityDistrict: "경기도 의정부시",
  },
  {
    id: "96",
    city: "경기도",
    district: "안양시",
    cityDistrict: "경기도 안양시",
  },
  {
    id: "97",
    city: "경기도",
    district: "만안구",
    cityDistrict: "경기도 만안구",
  },
  {
    id: "98",
    city: "경기도",
    district: "동안구",
    cityDistrict: "경기도 동안구",
  },
  {
    id: "99",
    city: "경기도",
    district: "부천시",
    cityDistrict: "경기도 부천시",
  },
  {
    id: "100",
    city: "경기도",
    district: "원미구",
    cityDistrict: "경기도 원미구",
  },
  {
    id: "101",
    city: "경기도",
    district: "소사구",
    cityDistrict: "경기도 소사구",
  },
  {
    id: "102",
    city: "경기도",
    district: "오정구",
    cityDistrict: "경기도 오정구",
  },
  {
    id: "103",
    city: "경기도",
    district: "광명시",
    cityDistrict: "경기도 광명시",
  },
  {
    id: "104",
    city: "경기도",
    district: "평택시",
    cityDistrict: "경기도 평택시",
  },
  {
    id: "105",
    city: "경기도",
    district: "동두천시",
    cityDistrict: "경기도 동두천시",
  },
  {
    id: "106",
    city: "경기도",
    district: "안산시",
    cityDistrict: "경기도 안산시",
  },
  {
    id: "107",
    city: "경기도",
    district: "상록구",
    cityDistrict: "경기도 상록구",
  },
  {
    id: "108",
    city: "경기도",
    district: "단원구",
    cityDistrict: "경기도 단원구",
  },
  {
    id: "109",
    city: "경기도",
    district: "고양시",
    cityDistrict: "경기도 고양시",
  },
  {
    id: "110",
    city: "경기도",
    district: "덕양구",
    cityDistrict: "경기도 덕양구",
  },
  {
    id: "111",
    city: "경기도",
    district: "일산동구",
    cityDistrict: "경기도 일산동구",
  },
  {
    id: "112",
    city: "경기도",
    district: "일산서구",
    cityDistrict: "경기도 일산서구",
  },
  {
    id: "113",
    city: "경기도",
    district: "과천시",
    cityDistrict: "경기도 과천시",
  },
  {
    id: "114",
    city: "경기도",
    district: "구리시",
    cityDistrict: "경기도 구리시",
  },
  {
    id: "115",
    city: "경기도",
    district: "남양주시",
    cityDistrict: "경기도 남양주시",
  },
  {
    id: "116",
    city: "경기도",
    district: "오산시",
    cityDistrict: "경기도 오산시",
  },
  {
    id: "117",
    city: "경기도",
    district: "시흥시",
    cityDistrict: "경기도 시흥시",
  },
  {
    id: "118",
    city: "경기도",
    district: "군포시",
    cityDistrict: "경기도 군포시",
  },
  {
    id: "119",
    city: "경기도",
    district: "의왕시",
    cityDistrict: "경기도 의왕시",
  },
  {
    id: "120",
    city: "경기도",
    district: "하남시",
    cityDistrict: "경기도 하남시",
  },
  {
    id: "121",
    city: "경기도",
    district: "용인시",
    cityDistrict: "경기도 용인시",
  },
  {
    id: "122",
    city: "경기도",
    district: "처인구",
    cityDistrict: "경기도 처인구",
  },
  {
    id: "123",
    city: "경기도",
    district: "기흥구",
    cityDistrict: "경기도 기흥구",
  },
  {
    id: "124",
    city: "경기도",
    district: "수지구",
    cityDistrict: "경기도 수지구",
  },
  {
    id: "125",
    city: "경기도",
    district: "파주시",
    cityDistrict: "경기도 파주시",
  },
  {
    id: "126",
    city: "경기도",
    district: "이천시",
    cityDistrict: "경기도 이천시",
  },
  {
    id: "127",
    city: "경기도",
    district: "안성시",
    cityDistrict: "경기도 안성시",
  },
  {
    id: "128",
    city: "경기도",
    district: "김포시",
    cityDistrict: "경기도 김포시",
  },
  {
    id: "129",
    city: "경기도",
    district: "화성시",
    cityDistrict: "경기도 화성시",
  },
  {
    id: "130",
    city: "경기도",
    district: "광주시",
    cityDistrict: "경기도 광주시",
  },
  {
    id: "131",
    city: "경기도",
    district: "양주시",
    cityDistrict: "경기도 양주시",
  },
  {
    id: "132",
    city: "경기도",
    district: "포천시",
    cityDistrict: "경기도 포천시",
  },
  {
    id: "133",
    city: "경기도",
    district: "여주시",
    cityDistrict: "경기도 여주시",
  },
  {
    id: "134",
    city: "경기도",
    district: "연천군",
    cityDistrict: "경기도 연천군",
  },
  {
    id: "135",
    city: "경기도",
    district: "가평군",
    cityDistrict: "경기도 가평군",
  },
  {
    id: "136",
    city: "경기도",
    district: "양평군",
    cityDistrict: "경기도 양평군",
  },
  {
    id: "137",
    city: "강원특별자치도",
    cityDistrict: "강원특별자치도",
  },
  {
    id: "138",
    city: "강원특별자치도",
    district: "춘천시",
    cityDistrict: "강원특별자치도 춘천시",
  },
  {
    id: "139",
    city: "강원특별자치도",
    district: "원주시",
    cityDistrict: "강원특별자치도 원주시",
  },
  {
    id: "140",
    city: "강원특별자치도",
    district: "강릉시",
    cityDistrict: "강원특별자치도 강릉시",
  },
  {
    id: "141",
    city: "강원특별자치도",
    district: "동해시",
    cityDistrict: "강원특별자치도 동해시",
  },
  {
    id: "142",
    city: "강원특별자치도",
    district: "태백시",
    cityDistrict: "강원특별자치도 태백시",
  },
  {
    id: "143",
    city: "강원특별자치도",
    district: "속초시",
    cityDistrict: "강원특별자치도 속초시",
  },
  {
    id: "144",
    city: "강원특별자치도",
    district: "삼척시",
    cityDistrict: "강원특별자치도 삼척시",
  },
  {
    id: "145",
    city: "강원특별자치도",
    district: "홍천군",
    cityDistrict: "강원특별자치도 홍천군",
  },
  {
    id: "146",
    city: "강원특별자치도",
    district: "횡성군",
    cityDistrict: "강원특별자치도 횡성군",
  },
  {
    id: "147",
    city: "강원특별자치도",
    district: "영월군",
    cityDistrict: "강원특별자치도 영월군",
  },
  {
    id: "148",
    city: "강원특별자치도",
    district: "평창군",
    cityDistrict: "강원특별자치도 평창군",
  },
  {
    id: "149",
    city: "강원특별자치도",
    district: "정선군",
    cityDistrict: "강원특별자치도 정선군",
  },
  {
    id: "150",
    city: "강원특별자치도",
    district: "철원군",
    cityDistrict: "강원특별자치도 철원군",
  },
  {
    id: "151",
    city: "강원특별자치도",
    district: "화천군",
    cityDistrict: "강원특별자치도 화천군",
  },
  {
    id: "152",
    city: "강원특별자치도",
    district: "양구군",
    cityDistrict: "강원특별자치도 양구군",
  },
  {
    id: "153",
    city: "강원특별자치도",
    district: "인제군",
    cityDistrict: "강원특별자치도 인제군",
  },
  {
    id: "154",
    city: "강원특별자치도",
    district: "고성군",
    cityDistrict: "강원특별자치도 고성군",
  },
  {
    id: "155",
    city: "강원특별자치도",
    district: "양양군",
    cityDistrict: "강원특별자치도 양양군",
  },
  {
    id: "156",
    city: "충청북도",
    cityDistrict: "충청북도",
  },
  {
    id: "157",
    city: "충청북도",
    district: "청주시",
    cityDistrict: "충청북도 청주시",
  },
  {
    id: "158",
    city: "충청북도",
    district: "상당구",
    cityDistrict: "충청북도 상당구",
  },
  {
    id: "159",
    city: "충청북도",
    district: "서원구",
    cityDistrict: "충청북도 서원구",
  },
  {
    id: "160",
    city: "충청북도",
    district: "흥덕구",
    cityDistrict: "충청북도 흥덕구",
  },
  {
    id: "161",
    city: "충청북도",
    district: "청원구",
    cityDistrict: "충청북도 청원구",
  },
  {
    id: "162",
    city: "충청북도",
    district: "충주시",
    cityDistrict: "충청북도 충주시",
  },
  {
    id: "163",
    city: "충청북도",
    district: "제천시",
    cityDistrict: "충청북도 제천시",
  },
  {
    id: "164",
    city: "충청북도",
    district: "보은군",
    cityDistrict: "충청북도 보은군",
  },
  {
    id: "165",
    city: "충청북도",
    district: "옥천군",
    cityDistrict: "충청북도 옥천군",
  },
  {
    id: "166",
    city: "충청북도",
    district: "영동군",
    cityDistrict: "충청북도 영동군",
  },
  {
    id: "167",
    city: "충청북도",
    district: "증평군",
    cityDistrict: "충청북도 증평군",
  },
  {
    id: "168",
    city: "충청북도",
    district: "진천군",
    cityDistrict: "충청북도 진천군",
  },
  {
    id: "169",
    city: "충청북도",
    district: "괴산군",
    cityDistrict: "충청북도 괴산군",
  },
  {
    id: "170",
    city: "충청북도",
    district: "음성군",
    cityDistrict: "충청북도 음성군",
  },
  {
    id: "171",
    city: "충청북도",
    district: "단양군",
    cityDistrict: "충청북도 단양군",
  },
  {
    id: "172",
    city: "충청남도",
    cityDistrict: "충청남도",
  },
  {
    id: "173",
    city: "충청남도",
    district: "천안시",
    cityDistrict: "충청남도 천안시",
  },
  {
    id: "174",
    city: "충청남도",
    district: "동남구",
    cityDistrict: "충청남도 동남구",
  },
  {
    id: "175",
    city: "충청남도",
    district: "서북구",
    cityDistrict: "충청남도 서북구",
  },
  {
    id: "176",
    city: "충청남도",
    district: "공주시",
    cityDistrict: "충청남도 공주시",
  },
  {
    id: "177",
    city: "충청남도",
    district: "보령시",
    cityDistrict: "충청남도 보령시",
  },
  {
    id: "178",
    city: "충청남도",
    district: "아산시",
    cityDistrict: "충청남도 아산시",
  },
  {
    id: "179",
    city: "충청남도",
    district: "서산시",
    cityDistrict: "충청남도 서산시",
  },
  {
    id: "180",
    city: "충청남도",
    district: "논산시",
    cityDistrict: "충청남도 논산시",
  },
  {
    id: "181",
    city: "충청남도",
    district: "계룡시",
    cityDistrict: "충청남도 계룡시",
  },
  {
    id: "182",
    city: "충청남도",
    district: "당진시",
    cityDistrict: "충청남도 당진시",
  },
  {
    id: "183",
    city: "충청남도",
    district: "금산군",
    cityDistrict: "충청남도 금산군",
  },
  {
    id: "184",
    city: "충청남도",
    district: "부여군",
    cityDistrict: "충청남도 부여군",
  },
  {
    id: "185",
    city: "충청남도",
    district: "서천군",
    cityDistrict: "충청남도 서천군",
  },
  {
    id: "186",
    city: "충청남도",
    district: "청양군",
    cityDistrict: "충청남도 청양군",
  },
  {
    id: "187",
    city: "충청남도",
    district: "홍성군",
    cityDistrict: "충청남도 홍성군",
  },
  {
    id: "188",
    city: "충청남도",
    district: "예산군",
    cityDistrict: "충청남도 예산군",
  },
  {
    id: "189",
    city: "충청남도",
    district: "태안군",
    cityDistrict: "충청남도 태안군",
  },
  {
    id: "190",
    city: "전북특별자치도",
    cityDistrict: "전북특별자치도",
  },
  {
    id: "191",
    city: "전북특별자치도",
    district: "전주시",
    cityDistrict: "전북특별자치도 전주시",
  },
  {
    id: "192",
    city: "전북특별자치도",
    district: "완산구",
    cityDistrict: "전북특별자치도 완산구",
  },
  {
    id: "193",
    city: "전북특별자치도",
    district: "덕진구",
    cityDistrict: "전북특별자치도 덕진구",
  },
  {
    id: "194",
    city: "전북특별자치도",
    district: "군산시",
    cityDistrict: "전북특별자치도 군산시",
  },
  {
    id: "195",
    city: "전북특별자치도",
    district: "익산시",
    cityDistrict: "전북특별자치도 익산시",
  },
  {
    id: "196",
    city: "전북특별자치도",
    district: "정읍시",
    cityDistrict: "전북특별자치도 정읍시",
  },
  {
    id: "197",
    city: "전북특별자치도",
    district: "남원시",
    cityDistrict: "전북특별자치도 남원시",
  },
  {
    id: "198",
    city: "전북특별자치도",
    district: "김제시",
    cityDistrict: "전북특별자치도 김제시",
  },
  {
    id: "199",
    city: "전북특별자치도",
    district: "완주군",
    cityDistrict: "전북특별자치도 완주군",
  },
  {
    id: "200",
    city: "전북특별자치도",
    district: "진안군",
    cityDistrict: "전북특별자치도 진안군",
  },
  {
    id: "201",
    city: "전북특별자치도",
    district: "무주군",
    cityDistrict: "전북특별자치도 무주군",
  },
  {
    id: "202",
    city: "전북특별자치도",
    district: "장수군",
    cityDistrict: "전북특별자치도 장수군",
  },
  {
    id: "203",
    city: "전북특별자치도",
    district: "임실군",
    cityDistrict: "전북특별자치도 임실군",
  },
  {
    id: "204",
    city: "전북특별자치도",
    district: "순창군",
    cityDistrict: "전북특별자치도 순창군",
  },
  {
    id: "205",
    city: "전북특별자치도",
    district: "고창군",
    cityDistrict: "전북특별자치도 고창군",
  },
  {
    id: "206",
    city: "전북특별자치도",
    district: "부안군",
    cityDistrict: "전북특별자치도 부안군",
  },
  {
    id: "207",
    city: "전라남도",
    cityDistrict: "전라남도",
  },
  {
    id: "208",
    city: "전라남도",
    district: "목포시",
    cityDistrict: "전라남도 목포시",
  },
  {
    id: "209",
    city: "전라남도",
    district: "여수시",
    cityDistrict: "전라남도 여수시",
  },
  {
    id: "210",
    city: "전라남도",
    district: "순천시",
    cityDistrict: "전라남도 순천시",
  },
  {
    id: "211",
    city: "전라남도",
    district: "나주시",
    cityDistrict: "전라남도 나주시",
  },
  {
    id: "212",
    city: "전라남도",
    district: "광양시",
    cityDistrict: "전라남도 광양시",
  },
  {
    id: "213",
    city: "전라남도",
    district: "담양군",
    cityDistrict: "전라남도 담양군",
  },
  {
    id: "214",
    city: "전라남도",
    district: "곡성군",
    cityDistrict: "전라남도 곡성군",
  },
  {
    id: "215",
    city: "전라남도",
    district: "구례군",
    cityDistrict: "전라남도 구례군",
  },
  {
    id: "216",
    city: "전라남도",
    district: "고흥군",
    cityDistrict: "전라남도 고흥군",
  },
  {
    id: "217",
    city: "전라남도",
    district: "보성군",
    cityDistrict: "전라남도 보성군",
  },
  {
    id: "218",
    city: "전라남도",
    district: "화순군",
    cityDistrict: "전라남도 화순군",
  },
  {
    id: "219",
    city: "전라남도",
    district: "장흥군",
    cityDistrict: "전라남도 장흥군",
  },
  {
    id: "220",
    city: "전라남도",
    district: "강진군",
    cityDistrict: "전라남도 강진군",
  },
  {
    id: "221",
    city: "전라남도",
    district: "해남군",
    cityDistrict: "전라남도 해남군",
  },
  {
    id: "222",
    city: "전라남도",
    district: "영암군",
    cityDistrict: "전라남도 영암군",
  },
  {
    id: "223",
    city: "전라남도",
    district: "무안군",
    cityDistrict: "전라남도 무안군",
  },
  {
    id: "224",
    city: "전라남도",
    district: "함평군",
    cityDistrict: "전라남도 함평군",
  },
  {
    id: "225",
    city: "전라남도",
    district: "영광군",
    cityDistrict: "전라남도 영광군",
  },
  {
    id: "226",
    city: "전라남도",
    district: "장성군",
    cityDistrict: "전라남도 장성군",
  },
  {
    id: "227",
    city: "전라남도",
    district: "완도군",
    cityDistrict: "전라남도 완도군",
  },
  {
    id: "228",
    city: "전라남도",
    district: "진도군",
    cityDistrict: "전라남도 진도군",
  },
  {
    id: "229",
    city: "전라남도",
    district: "신안군",
    cityDistrict: "전라남도 신안군",
  },
  {
    id: "230",
    city: "경상북도",
    cityDistrict: "경상북도",
  },
  {
    id: "231",
    city: "경상북도",
    district: "포항시",
    cityDistrict: "경상북도 포항시",
  },
  {
    id: "232",
    city: "경상북도",
    district: "남구",
    cityDistrict: "경상북도 남구",
  },
  {
    id: "233",
    city: "경상북도",
    district: "북구",
    cityDistrict: "경상북도 북구",
  },
  {
    id: "234",
    city: "경상북도",
    district: "경주시",
    cityDistrict: "경상북도 경주시",
  },
  {
    id: "235",
    city: "경상북도",
    district: "김천시",
    cityDistrict: "경상북도 김천시",
  },
  {
    id: "236",
    city: "경상북도",
    district: "안동시",
    cityDistrict: "경상북도 안동시",
  },
  {
    id: "237",
    city: "경상북도",
    district: "구미시",
    cityDistrict: "경상북도 구미시",
  },
  {
    id: "238",
    city: "경상북도",
    district: "영주시",
    cityDistrict: "경상북도 영주시",
  },
  {
    id: "239",
    city: "경상북도",
    district: "영천시",
    cityDistrict: "경상북도 영천시",
  },
  {
    id: "240",
    city: "경상북도",
    district: "상주시",
    cityDistrict: "경상북도 상주시",
  },
  {
    id: "241",
    city: "경상북도",
    district: "문경시",
    cityDistrict: "경상북도 문경시",
  },
  {
    id: "242",
    city: "경상북도",
    district: "경산시",
    cityDistrict: "경상북도 경산시",
  },
  {
    id: "243",
    city: "경상북도",
    district: "의성군",
    cityDistrict: "경상북도 의성군",
  },
  {
    id: "244",
    city: "경상북도",
    district: "청송군",
    cityDistrict: "경상북도 청송군",
  },
  {
    id: "245",
    city: "경상북도",
    district: "영양군",
    cityDistrict: "경상북도 영양군",
  },
  {
    id: "246",
    city: "경상북도",
    district: "영덕군",
    cityDistrict: "경상북도 영덕군",
  },
  {
    id: "247",
    city: "경상북도",
    district: "청도군",
    cityDistrict: "경상북도 청도군",
  },
  {
    id: "248",
    city: "경상북도",
    district: "고령군",
    cityDistrict: "경상북도 고령군",
  },
  {
    id: "249",
    city: "경상북도",
    district: "성주군",
    cityDistrict: "경상북도 성주군",
  },
  {
    id: "250",
    city: "경상북도",
    district: "칠곡군",
    cityDistrict: "경상북도 칠곡군",
  },
  {
    id: "251",
    city: "경상북도",
    district: "예천군",
    cityDistrict: "경상북도 예천군",
  },
  {
    id: "252",
    city: "경상북도",
    district: "봉화군",
    cityDistrict: "경상북도 봉화군",
  },
  {
    id: "253",
    city: "경상북도",
    district: "울진군",
    cityDistrict: "경상북도 울진군",
  },
  {
    id: "254",
    city: "경상북도",
    district: "울릉군",
    cityDistrict: "경상북도 울릉군",
  },
  {
    id: "255",
    city: "경상남도",
    cityDistrict: "경상남도",
  },
  {
    id: "256",
    city: "경상남도",
    district: "창원시",
    cityDistrict: "경상남도 창원시",
  },
  {
    id: "257",
    city: "경상남도",
    district: "의창구",
    cityDistrict: "경상남도 의창구",
  },
  {
    id: "258",
    city: "경상남도",
    district: "성산구",
    cityDistrict: "경상남도 성산구",
  },
  {
    id: "259",
    city: "경상남도",
    district: "마산합포구",
    cityDistrict: "경상남도 마산합포구",
  },
  {
    id: "260",
    city: "경상남도",
    district: "마산회원구",
    cityDistrict: "경상남도 마산회원구",
  },
  {
    id: "261",
    city: "경상남도",
    district: "진해구",
    cityDistrict: "경상남도 진해구",
  },
  {
    id: "262",
    city: "경상남도",
    district: "진주시",
    cityDistrict: "경상남도 진주시",
  },
  {
    id: "263",
    city: "경상남도",
    district: "통영시",
    cityDistrict: "경상남도 통영시",
  },
  {
    id: "264",
    city: "경상남도",
    district: "사천시",
    cityDistrict: "경상남도 사천시",
  },
  {
    id: "265",
    city: "경상남도",
    district: "김해시",
    cityDistrict: "경상남도 김해시",
  },
  {
    id: "266",
    city: "경상남도",
    district: "밀양시",
    cityDistrict: "경상남도 밀양시",
  },
  {
    id: "267",
    city: "경상남도",
    district: "거제시",
    cityDistrict: "경상남도 거제시",
  },
  {
    id: "268",
    city: "경상남도",
    district: "양산시",
    cityDistrict: "경상남도 양산시",
  },
  {
    id: "269",
    city: "경상남도",
    district: "의령군",
    cityDistrict: "경상남도 의령군",
  },
  {
    id: "270",
    city: "경상남도",
    district: "함안군",
    cityDistrict: "경상남도 함안군",
  },
  {
    id: "271",
    city: "경상남도",
    district: "창녕군",
    cityDistrict: "경상남도 창녕군",
  },
  {
    id: "272",
    city: "경상남도",
    district: "고성군",
    cityDistrict: "경상남도 고성군",
  },
  {
    id: "273",
    city: "경상남도",
    district: "남해군",
    cityDistrict: "경상남도 남해군",
  },
  {
    id: "274",
    city: "경상남도",
    district: "하동군",
    cityDistrict: "경상남도 하동군",
  },
  {
    id: "275",
    city: "경상남도",
    district: "산청군",
    cityDistrict: "경상남도 산청군",
  },
  {
    id: "276",
    city: "경상남도",
    district: "함양군",
    cityDistrict: "경상남도 함양군",
  },
  {
    id: "277",
    city: "경상남도",
    district: "거창군",
    cityDistrict: "경상남도 거창군",
  },
  {
    id: "278",
    city: "경상남도",
    district: "합천군",
    cityDistrict: "경상남도 합천군",
  },
  {
    id: "279",
    city: "제주특별자치도",
    cityDistrict: "제주특별자치도",
  },
  {
    id: "280",
    city: "제주특별자치도",
    district: "제주시",
    cityDistrict: "제주특별자치도 제주시",
  },
  {
    id: "281",
    city: "제주특별자치도",
    district: "서귀포시",
    cityDistrict: "제주특별자치도 서귀포시",
  },
];
